- name: Build Toolbox
  command: meson compile -C builddir
  args:
    chdir: '{{ zuul.project.src_dir }}'
    creates: builddir/src/toolbox

- name: Install Toolbox
  become: yes
  command: meson install -C builddir
  args:
    chdir: '{{ zuul.project.src_dir }}'
    creates: /usr/local/bin/toolbox
